name: ArgoCD Automation

on:
  workflow_dispatch:
jobs:
  run_argocd_commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        sudo mv argocd-linux-amd64 /usr/local/bin/argocd


    - name: Login to ArgoCD
      run: |
        argocd login ${{ variables.url }} --username admin --password ${{ secrets.ARGOCD_ADMIN_PASSWORD }} --insecure

    - name: Run ArgoCD Commands
      run: |
        # Example ArgoCD commands:
        argocd app list
        # argocd app create my-app --repo https://github.com/my-org/my-repo.git --path my-app-path --dest-server https://kubernetes.default.svc --dest-namespace my-namespace
        # argocd app sync my-app
        # argocd app get my-app
        # argocd app delete my-app --cascade
        # Add your desired ArgoCD commands here.
