name: ArgoCD Automation

on:
  workflow_dispatch:
jobs:
  run_argocd_commands:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        sudo mv argocd-linux-amd64 /usr/local/bin/argocd


    - name: Login to ArgoCD
      run: |
        argocd login ${{ variables.URL }} --username admin --password ${{ secrets.ARGOCD_ADMIN_PASSWORD }} --insecure

    - name: Run ArgoCD Commands
      run: |
        # Example ArgoCD commands:
        argocd repo add https://github.com/nizanim2/docs.git
        argocd app create ingress-controller --repo https://github.com/nizanim2/docs.git --path helm-charts/ingress-nginx --dest-server https://kubernetes.default.svc --dest-namespace ingress-controller --sync-option CreateNamespace=true
        argocd app sync ingress-controller
        argocd app create kube-prometheus-stack --repo https://github.com/nizanim2/docs.git --path helm-charts/kube-prometheus-stack --dest-server https://kubernetes.default.svc --dest-namespace prometheus-stack --sync-option CreateNamespace=true
        argocd app sync kube-prometheus-stack
        argocd app create statuspage --repo https://github.com/nizanim2/docs.git --path helm-charts/statuspage-helm --dest-server https://kubernetes.default.svc --dest-namespace statuspage --sync-option CreateNamespace=true
        argocd app sync statuspage
        # argocd app get my-app
        # argocd app delete my-app --cascade
        # Add your desired ArgoCD commands here.
